import { recordReference } from "../domain/references.js";
import type {
  EvidenceReference,
  RecordKind,
  RecordStatus,
  RelationshipPayload,
  SemanticRecord,
  ValidatedRepository,
} from "../domain/types.js";

const marker = "<!-- Generated by LORE. Do not edit directly. -->";
const ref = (repository: ValidatedRepository, record: SemanticRecord) =>
  recordReference(repository.manifest.repository.id, record);
const effectiveStatus = (repository: ValidatedRepository, record: SemanticRecord) =>
  repository.effectiveStatus.get(ref(repository, record)) ?? record.status;
const active = (repository: ValidatedRepository, record: SemanticRecord) =>
  effectiveStatus(repository, record) !== "superseded";
const edge = (record: SemanticRecord) => record.payload as unknown as RelationshipPayload;
const relationships = (repository: ValidatedRepository) => repository.records
  .filter((record) => record.kind === "relationship" && active(repository, record))
  .sort((a, b) => a.id.localeCompare(b.id));

type LoreNodeKind = Exclude<RecordKind, "relationship">;
type DeciduousNodeType = "goal" | "option" | "decision" | "action" | "outcome" | "observation" | "revisit";
type DeciduousStatus = "pending" | "active" | "completed" | "rejected" | "superseded" | "abandoned";

const deciduousTypes: Record<LoreNodeKind, DeciduousNodeType> = {
  repository: "outcome",
  component: "outcome",
  decision: "decision",
  finding: "observation",
  constraint: "goal",
  procedure: "action",
};

const deciduousStatuses: Record<RecordStatus, DeciduousStatus> = {
  draft: "pending",
  active: "active",
  superseded: "superseded",
  deprecated: "abandoned",
  resolved: "completed",
  withdrawn: "abandoned",
};

export function deciduousNodeType(kind: LoreNodeKind): DeciduousNodeType {
  return deciduousTypes[kind];
}

function deciduousStatus(status: RecordStatus): DeciduousStatus {
  return deciduousStatuses[status];
}

function deciduousNodeId(record: SemanticRecord): string {
  return `lore.${record.kind}.${record.id}.r${record.revision}`;
}

function deciduousEvidence(evidence: EvidenceReference): string {
  const location = evidence.symbol
    ? `${evidence.path}#${evidence.symbol}`
    : evidence.lines
      ? `${evidence.path}:L${evidence.lines.start}-L${evidence.lines.end}`
      : evidence.path;
  return `commit:${evidence.revision}#${location}`;
}

export function renderWhyThisRepository(repository: ValidatedRepository): string {
  const links = relationships(repository);
  if (links.length === 0) return `${marker}\n# Why this repository\n\nNo accepted causal relationships are recorded yet.\n`;
  const records = new Map(repository.records.map((record) => [ref(repository, record), record]));
  const lines = links.map((relationship) => {
    const payload = edge(relationship);
    const source = records.get(payload.from);
    const target = records.get(payload.to);
    const evidence = relationship.evidence.map(({ path, revision }) => `${path} at ${revision}`).join("; ");
    return `- **${target?.title ?? payload.to}** ${payload.relation} from ${source?.title ?? payload.from}: ${payload.rationale} Evidence: ${evidence}.`;
  });
  return `${marker}\n# Why this repository\n\nThis view is generated from accepted LORE relationship records. It is explanatory and non-authoritative.\n\n${lines.join("\n")}\n`;
}

export function renderDeciduousCompatibility(repository: ValidatedRepository): string {
  const semanticRecords = repository.records
    .filter((record): record is SemanticRecord & { kind: LoreNodeKind } => record.kind !== "relationship")
    .sort((a, b) => ref(repository, a).localeCompare(ref(repository, b)));
  const nodeIds = new Map(
    semanticRecords.map((record) => [ref(repository, record), deciduousNodeId(record)]),
  );
  const nodes = semanticRecords.map((record) => {
    const loreStatus = effectiveStatus(repository, record);
    const status = deciduousStatus(loreStatus);
    return {
      id: deciduousNodeId(record),
      type: deciduousNodeType(record.kind),
      status,
      lifecycle_status: status,
      current: status === "active",
      title: record.title,
      description: record.summary,
      evidence: record.evidence.map(deciduousEvidence),
      lore_ref: ref(repository, record),
      lore_kind: record.kind,
      lore_status: loreStatus,
    };
  });
  const edges = relationships(repository).map((relationship) => {
    const payload = edge(relationship);
    return {
      id: deciduousNodeId(relationship),
      from: nodeIds.get(payload.from) ?? payload.from,
      to: nodeIds.get(payload.to) ?? payload.to,
      type: payload.relation,
      rationale: payload.rationale,
      evidence: relationship.evidence.map(deciduousEvidence),
      lore_ref: ref(repository, relationship),
    };
  });
  return `${JSON.stringify({
    schema: "lore-deciduous-compat/v1",
    repository: repository.manifest.repository.id,
    native_contract: {
      node_types: ["goal", "option", "decision", "action", "outcome", "observation", "revisit"],
      statuses: ["pending", "active", "completed", "rejected", "superseded", "abandoned"],
      edge_types: ["leads_to", "chosen", "rejected", "requires", "blocks", "enables", "supersedes"],
    },
    nodes,
    edges,
  }, null, 2)}\n`;
}
