import { recordReference } from "../domain/references.js";
import type { RelationshipPayload, SemanticRecord, ValidatedRepository } from "../domain/types.js";

const marker = "<!-- Generated by LORE. Do not edit directly. -->";
const ref = (repository: ValidatedRepository, record: SemanticRecord) =>
  recordReference(repository.manifest.repository.id, record);
const active = (repository: ValidatedRepository, record: SemanticRecord) =>
  repository.effectiveStatus.get(ref(repository, record)) !== "superseded";
const edge = (record: SemanticRecord) => record.payload as unknown as RelationshipPayload;
const relationships = (repository: ValidatedRepository) => repository.records
  .filter((record) => record.kind === "relationship" && active(repository, record))
  .sort((a, b) => a.id.localeCompare(b.id));

export function renderWhyThisRepository(repository: ValidatedRepository): string {
  const links = relationships(repository);
  if (links.length === 0) return `${marker}\n# Why this repository\n\nNo accepted causal relationships are recorded yet.\n`;
  const records = new Map(repository.records.map((record) => [ref(repository, record), record]));
  const lines = links.map((relationship) => {
    const payload = edge(relationship);
    const source = records.get(payload.from);
    const target = records.get(payload.to);
    const evidence = relationship.evidence.map(({ path, revision }) => `${path} at ${revision}`).join("; ");
    return `- **${target?.title ?? payload.to}** ${payload.relation} from ${source?.title ?? payload.from}: ${payload.rationale} Evidence: ${evidence}.`;
  });
  return `${marker}\n# Why this repository\n\nThis view is generated from accepted LORE relationship records. It is explanatory and non-authoritative.\n\n${lines.join("\n")}\n`;
}

export function renderDeciduousCompatibility(repository: ValidatedRepository): string {
  const nodes = repository.records
    .filter((record) => record.kind !== "relationship" && active(repository, record))
    .sort((a, b) => ref(repository, a).localeCompare(ref(repository, b)))
    .map((record) => ({
      id: ref(repository, record),
      type: record.kind,
      status: repository.effectiveStatus.get(ref(repository, record)) ?? record.status,
      title: record.title,
      description: record.summary,
      evidence: record.evidence.map(({ revision, path }) => ({ revision, path })),
    }));
  const edges = relationships(repository).map((relationship) => ({
    id: ref(repository, relationship),
    from: edge(relationship).from,
    to: edge(relationship).to,
    type: edge(relationship).relation,
    rationale: edge(relationship).rationale,
    evidence: relationship.evidence.map(({ revision, path }) => ({ revision, path })),
  }));
  return `${JSON.stringify({ schema: "lore-deciduous-compat/v1", repository: repository.manifest.repository.id, nodes, edges }, null, 2)}\n`;
}
