import { ok } from "../domain/errors.js";
import type {
  SemanticRecord,
  ValidatedRepository,
  ValidationResult,
} from "../domain/types.js";
import {
  renderArchitecture,
  renderAuthorityAndFileOwnership,
  renderCliReference,
  renderDataModelReference,
  renderDecisions,
  renderMaintenanceWorkflow,
  renderProposalReview,
  renderReadme,
  renderRepositoryCard,
  renderTrustModel,
} from "./templates.js";

const marker = "<!-- Generated by LORE. Do not edit directly. -->";

function activeRecords(
  repository: ValidatedRepository,
  kind: SemanticRecord["kind"],
): SemanticRecord[] {
  return repository.records
    .filter((record) => {
      if (record.kind !== kind) return false;
      const reference = `lore://${repository.manifest.repository.id}/${record.kind}/${record.id}@${record.revision}`;
      return repository.effectiveStatus.get(reference) !== "superseded";
    })
    .sort((left, right) =>
      left.title.localeCompare(right.title) || left.id.localeCompare(right.id),
    );
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/#/g, "\\#");
}

function renderCompleteCatalog(repository: ValidatedRepository): string {
  const components = repository.records
    .filter((record) => record.kind === "component")
    .sort((left, right) =>
      left.title.localeCompare(right.title) || left.revision - right.revision,
    );
  const rows = components
    .map((component) => {
      const reference = `lore://${repository.manifest.repository.id}/${component.kind}/${component.id}@${component.revision}`;
      const status = repository.effectiveStatus.get(reference) ?? component.status;
      const evidence = component.evidence
        .map(({ path, revision }) => `\`${path}\` at \`${revision}\``)
        .join("; ");
      return `| ${escapeTable(component.title)} | ${status} | ${escapeTable(component.summary)} | ${escapeTable(evidence || "None recorded")} |`;
    })
    .join("\n");
  return `${marker}
# Component catalog

| Component | Status | Summary | Evidence |
|---|---|---|---|
${rows}
`;
}

function renderRecordList(selected: SemanticRecord[], emptyMessage: string): string {
  if (selected.length === 0) return emptyMessage;
  return selected
    .map((record) => {
      const evidence = record.evidence
        .map(({ path, revision }) => `\`${path}\` at \`${revision}\``)
        .join(", ");
      return `- **${record.title}:** ${record.summary} Evidence: ${evidence}.`;
    })
    .join("\n");
}

function renderRevisionSafeGuide(repository: ValidatedRepository): string {
  return `${marker}
# Maintainer guide

LORE treats maintainer output as untrusted. Read \`${repository.manifest.maintenance.skill}\`, inspect the exact-revision evidence in the context packet, and return exactly one \`lore-proposal/v1\` artifact.

## Maintenance cycle

1. Record the exact base revision, then run \`lore extract\` and \`lore validate\`.
2. Define a bounded task and run \`lore context <task.yaml>\`.
3. Follow the repository-local skill and write the proposal to \`${repository.manifest.paths.proposals}/\`.
4. Run \`lore validate-proposal <proposal.yaml>\`.
5. Review semantic correctness, identity, evidence, uncertainty, and supersession.
6. Run \`lore apply <proposal.yaml>\` only after review.
7. Review and commit the accepted transaction and regenerated outputs.
8. Compare the committed base and target with \`lore diff\`, then run \`lore project --check\` and \`lore verify-self\`.

## Accepted procedures

${renderRecordList(activeRecords(repository, "procedure"), "No active procedure records.")}

## Active constraints

${renderRecordList(activeRecords(repository, "constraint"), "No active constraints.")}

Never edit generated documentation, extracted facts, accepted records, or transaction receipts directly.
`;
}

function renderRevisionSafeAdoptionTutorial(
  repository: ValidatedRepository,
): string {
  return `${marker}
# Adopt LORE

This tutorial installs LORE in an existing Git repository, establishes the trust root, and proves that the repository converges to deterministic state.

## 1. Start from a clean Git repository

\`\`\`bash
git status --short
npm install --save-dev @laurajoyhutchins/lore
npm exec -- lore version --json
\`\`\`

Commit or discard unrelated work before initialization. LORE evidence and proposal validation are revision-sensitive.

## 2. Install the bootstrap trust root

\`\`\`bash
npm exec -- lore init --id example-repository --name "Example Repository"
\`\`\`

Review \`lore.yaml\`, \`BOOTSTRAP.md\`, \`schemas/\`, and \`${repository.manifest.maintenance.skill}\`. Initialization must not silently replace accepted records or transactions.

## 3. Generate deterministic facts

\`\`\`bash
npm exec -- lore extract
npm exec -- lore validate
\`\`\`

Inspect \`${repository.manifest.paths.extracted}/\`. Extracted facts describe repository state but do not assert architectural intent.

## 4. Generate initial projections

\`\`\`bash
npm exec -- lore project
npm exec -- lore project --check
\`\`\`

Generated files are views. Do not edit them directly.

## 5. Commit the bootstrap state

\`\`\`bash
git add .
git commit -m "chore: initialize LORE"
\`\`\`

The first maintainer context must point at a committed exact revision so that proposal evidence can be validated against Git.

## 6. Complete semantic orientation

Create a bounded task describing the repository purpose, components, decisions, constraints, findings, and procedures that need review. Run:

\`\`\`bash
npm exec -- lore context .lore/tasks/initial-orientation.yaml \\
  > .lore/context/initial-orientation.yaml
\`\`\`

Give that packet and the repository-local skill to a human or model maintainer. The required output is exactly one \`lore-proposal/v1\` artifact.

## 7. Validate and apply the first proposal

\`\`\`bash
npm exec -- lore validate-proposal .lore/proposals/initial-orientation.yaml
npm exec -- lore apply .lore/proposals/initial-orientation.yaml
\`\`\`

Review the proposal semantically before applying it. Schema validity does not prove that an interpretation is correct.

## 8. Commit the accepted transaction

Review the new record revisions, transaction receipt, and regenerated projections before committing them.

\`\`\`bash
git add .
git commit -m "docs: establish repository knowledge"
\`\`\`

## 9. Prove convergence

\`\`\`bash
npm exec -- lore extract --check
npm exec -- lore validate
npm exec -- lore project --check
npm exec -- lore verify-self
git diff --exit-code
\`\`\`

The final command proves that the committed trust root, accepted records, extracted facts, transaction history, and projections are converged.

`;
}

export function projectRepository(
  repository: ValidatedRepository,
): Promise<ValidationResult<Map<string, string>>> {
  const files = new Map<string, string>();
  for (const projection of repository.manifest.projections) {
    const renderers = {
      readme: renderReadme,
      "repository-card": renderRepositoryCard,
      architecture: renderArchitecture,
      "component-catalog": renderCompleteCatalog,
      "current-decisions": renderDecisions,
      "maintainer-guide": renderRevisionSafeGuide,
      "trust-model": renderTrustModel,
      "authority-and-file-ownership": renderAuthorityAndFileOwnership,
      "adoption-tutorial": renderRevisionSafeAdoptionTutorial,
      "maintenance-workflow": renderMaintenanceWorkflow,
      "proposal-review": renderProposalReview,
      "cli-reference": renderCliReference,
      "data-model-reference": renderDataModelReference,
    };
    const content = renderers[projection.id](repository);
    files.set(
      projection.output,
      content.replace(/\r\n/g, "\n").replace(/\n*$/, "\n"),
    );
  }
  return Promise.resolve(ok(files));
}
