import { recordReference } from "../domain/references.js";
import type {
  EvidenceReference,
  RecordKind,
  SemanticRecord,
  ValidatedRepository,
} from "../domain/types.js";

const marker = "<!-- Generated by LORE. Do not edit directly. -->";
const esc = (value: string) => value.replace(/\|/g, "\\|").replace(/#/g, "\\#");
const active = (record: SemanticRecord, repository: ValidatedRepository) =>
  repository.effectiveStatus.get(
    recordReference(repository.manifest.repository.id, record),
  ) !== "superseded";

const records = (
  repository: ValidatedRepository,
  kind: RecordKind,
): SemanticRecord[] =>
  repository.records
    .filter((record) => record.kind === kind && active(record, repository))
    .sort((left, right) =>
      left.title.localeCompare(right.title) || left.id.localeCompare(right.id),
    );

const firstRecord = (
  repository: ValidatedRepository,
  kind: RecordKind,
): SemanticRecord | undefined => records(repository, kind)[0];

const evidenceLabel = (evidence: EvidenceReference): string => {
  const location = evidence.symbol
    ? `${evidence.path}#${evidence.symbol}`
    : evidence.lines
      ? `${evidence.path}#L${evidence.lines.start}-L${evidence.lines.end}`
      : evidence.path;
  return `\`${location}\` at \`${evidence.revision}\``;
};

const renderEvidence = (record: SemanticRecord): string =>
  record.evidence.length === 0
    ? "Evidence: none recorded."
    : `Evidence: ${record.evidence.map(evidenceLabel).join(", ")}.`;

const renderRecordList = (
  selected: SemanticRecord[],
  emptyMessage: string,
): string =>
  selected.length === 0
    ? emptyMessage
    : selected
        .map(
          (record) =>
            `- **${esc(record.title)}:** ${record.summary} ${renderEvidence(record)}`,
        )
        .join("\n");

const renderRecordSections = (
  selected: SemanticRecord[],
  emptyMessage: string,
  headingLevel = 2,
): string =>
  selected.length === 0
    ? emptyMessage
    : selected
        .map(
          (record) =>
            `${"#".repeat(headingLevel)} ${esc(record.title)}\n\n${record.summary}\n\n${renderEvidence(record)}\n`,
        )
        .join("\n");

const CLI_REFERENCE = [
  ["version", "`lore version [--json]`", "Report the installed package and schema versions without requiring a LORE repository."],
  ["init", "`lore init [--id <id>] [--name <name>] [--force]`", "Install the bootstrap trust root, schemas, maintainer skill, and manifest."],
  ["extract", "`lore extract [--check]`", "Regenerate deterministic repository facts or fail when committed facts are stale."],
  ["validate", "`lore validate`", "Validate the manifest, schemas, records, evidence, paths, and semantic invariants."],
  ["project", "`lore project [--check]`", "Regenerate deterministic documentation projections or fail when checked-in projections are stale."],
  ["context", "`lore context <task.yaml>`", "Create a maintainer context packet containing bounded records, evidence, instructions, and the proposal destination."],
  ["hydrate", "`lore hydrate <task.yaml>`", "Select and explain bounded task context without wrapping it in the maintainer protocol."],
  ["validate-proposal", "`lore validate-proposal <proposal.yaml>`", "Treat a proposal as untrusted and validate it without applying changes."],
  ["apply", "`lore apply <proposal.yaml>`", "Plan and transactionally apply a validated proposal, write its receipt, and regenerate affected projections."],
  ["diff", "`lore diff <base> <target> [--json]`", "Describe semantic and extracted-fact changes between two safely resolved Git revisions."],
  ["explain", "`lore explain <record-ref> [--json]`", "Explain a record, its effective status, lineage, relationships, evidence, and transactions."],
  ["verify-self", "`lore verify-self`", "Verify LORE's trust root, facts, records, projections, hydration, history, and deterministic outputs."],
  ["demo", "`lore demo`", "Exercise the self-hosting lifecycle in an isolated demonstration repository."],
] as const;

export function renderReadme(repository: ValidatedRepository) {
  return `${marker}
# ${esc(repository.manifest.repository.name)}

**LORE Organizes Repository Evidence** is an agent-neutral, Git-backed system for turning repository evidence and reviewed semantic records into human documentation and bounded maintainer context.

> **Project status:** pre-1.0 and under active development. The documented CLI is the supported public surface. Commands and schemas may change before 1.0.

## What LORE does

LORE separates repository knowledge into two layers:

- **Deterministic facts** extracted from source, configuration, package metadata, imports, and tests.
- **Reviewed semantic records** that capture intent, architecture, decisions, constraints, findings, and procedures that code alone cannot prove.

From those inputs, LORE produces deterministic documentation projections, explainable task-context hydration, semantic history comparisons, and validated append-only maintenance transactions.

LORE does not host an LLM, require a model provider, run autonomous schedules, use a vector database, or treat an agent identity as authorization. It is compatible with external development workflows, including Superpowers, but does not depend on them.

## Requirements

For the installed CLI:

- Git
- Node.js 22 or newer

## Install

Install LORE as a development dependency in the repository it will maintain:

\`\`\`bash
npm install --save-dev @laurajoyhutchins/lore
npm exec -- lore --help
npm exec -- lore version --json
\`\`\`

Initialize a Git repository with LORE's trust root, schemas, and maintainer skill:

\`\`\`bash
npm exec -- lore init --id example-repository --name "Example Repository"
npm exec -- lore extract
npm exec -- lore validate
npm exec -- lore project
\`\`\`

The npm package is **CLI-only**. Internal TypeScript modules, generated declaration shapes, and source paths are not supported library APIs. Use the documented \`lore\` commands and their documented machine-readable output.

## Core workflow

1. \`lore init\` installs the bootstrap trust root in a repository.
2. \`lore extract\` regenerates deterministic repository facts.
3. \`lore validate\` checks manifests, schemas, records, evidence, paths, and semantic invariants.
4. \`lore project\` regenerates human-facing documentation.
5. \`lore context\` and \`lore hydrate\` select bounded, explainable task context.
6. \`lore validate-proposal\` treats maintainer output as untrusted and validates it against the public protocol.
7. \`lore apply\` plans and records accepted changes transactionally.
8. \`lore diff\` and \`lore explain\` describe semantic history.
9. \`lore verify-self\` checks that LORE's own trust root, facts, records, projections, history, and deterministic outputs remain coherent.

Run \`npm exec -- lore --help\` for the command list. LORE is self-hosting: this README and the files under \`docs/generated/\` are projections produced by LORE itself.

## Source development

Contributors building LORE from source also need Corepack and pnpm 10.14.0:

\`\`\`bash
node scripts/restore-verified-lockfile.mjs
corepack enable
corepack pnpm install --frozen-lockfile
corepack pnpm typecheck
corepack pnpm lint
corepack pnpm test
corepack pnpm build
corepack pnpm lore --help
corepack pnpm lore verify-self
\`\`\`

The standard \`pnpm-lock.yaml\` is restored byte-for-byte from the content-addressed members under \`artifacts/verified-lockfile/\`. The release gate verifies every member, the reconstructed SHA-256, and the Git blob identity before installation, then removes gate-created temporary state before checking for a clean tree.

## Trust model

Repository documents, paths, Git revisions, source files, and maintainer proposals are untrusted inputs. LORE is designed to fail closed when it cannot prove schema validity, repository containment, evidence provenance, revision identity, append-only history, transactional integrity, or deterministic output.

Generated prose is useful but non-authoritative. Authority is explicit by concern: source code owns implemented behavior; \`lore.yaml\` and schemas own repository and protocol contracts; extracted facts are deterministic observations of repository state; accepted semantic records own reviewed knowledge; accepted transactions are immutable receipts of applied proposals; and the maintenance skill owns the maintainer protocol.

## Documentation

- [Adopt LORE](docs/generated/tutorials/adopt-lore.md)
- [Maintain repository knowledge](docs/generated/how-to/maintain-knowledge.md)
- [Review a proposal](docs/generated/how-to/review-a-proposal.md)
- [CLI reference](docs/generated/reference/cli.md)
- [Data model reference](docs/generated/reference/data-model.md)
- [Trust model](docs/generated/explanation/trust-model.md)
- [Authority and file ownership](docs/generated/explanation/authority-and-file-ownership.md)
- [Bootstrap trust root](BOOTSTRAP.md)
- [Design specification](docs/superpowers/specs/2026-07-28-lore-design.md)
- [Release operations](docs/releasing.md)
- [Public release readiness](docs/public-release-readiness.md)
- [Generated architecture](docs/generated/architecture.md)
- [Generated component catalog](docs/generated/component-catalog.md)
- [Generated current decisions](docs/generated/current-decisions.md)
- [Generated maintainer guide](docs/generated/maintainer-guide.md)
- [Maintainer skill](skills/maintain-repository-documentation/SKILL.md)
- [Contribution guide](CONTRIBUTING.md)
- [Security policy](SECURITY.md)

## Contributing and security

Contributions are welcome within the repository's evidence, determinism, and append-only-history contracts. Read [CONTRIBUTING.md](CONTRIBUTING.md) before changing source, schemas, semantic records, or generated documentation.

Report suspected vulnerabilities privately as described in [SECURITY.md](SECURITY.md). Do not disclose exploit details in a public issue.

## License

LORE is licensed under the [Apache License 2.0](LICENSE).
`;
}

export function renderRepositoryCard(repository: ValidatedRepository) {
  const repositoryRecord = firstRecord(repository, "repository");
  const components = records(repository, "component");
  const decisions = records(repository, "decision");
  const constraints = records(repository, "constraint");
  const findings = records(repository, "finding");
  const procedures = records(repository, "procedure");
  return `${marker}
# Repository card

- ID: \`${repository.manifest.repository.id}\`
- Purpose: ${repositoryRecord?.summary ?? "No active repository record."}
- Records: ${repository.records.length}
- Active components: ${components.length}
- Active decisions: ${decisions.length}
- Active constraints: ${constraints.length}
- Active findings: ${findings.length}
- Active procedures: ${procedures.length}

## Major components

${renderRecordList(components, "No active component records.")}

## Verification

Run \`lore validate\`, \`lore project --check\`, and \`lore verify-self\` from a clean repository checkout.
`;
}

export function renderArchitecture(repository: ValidatedRepository) {
  const repositoryRecord = firstRecord(repository, "repository");
  return `${marker}
# Architecture

${repositoryRecord?.summary ?? "No active repository record."}

## Components

${renderRecordSections(records(repository, "component"), "No active component records.", 3)}

## Active decisions

${renderRecordList(records(repository, "decision"), "No active decisions.")}

## Active constraints

${renderRecordList(records(repository, "constraint"), "No active constraints.")}

## Known findings

${renderRecordList(records(repository, "finding"), "No active findings.")}
`;
}

export function renderCatalog(repository: ValidatedRepository) {
  const components = records(repository, "component");
  return `${marker}
# Component catalog

| Component | Status | Summary | Evidence |
|---|---|---|---|
${components
  .map(
    (component) =>
      `| ${esc(component.title)} | ${repository.effectiveStatus.get(
        recordReference(repository.manifest.repository.id, component),
      ) ?? component.status} | ${esc(component.summary)} | ${esc(
        component.evidence.map(evidenceLabel).join("; ") || "None recorded",
      )} |`,
  )
  .join("\n")}
`;
}

export function renderDecisions(repository: ValidatedRepository) {
  return `${marker}
# Current decisions

${renderRecordSections(records(repository, "decision"), "No active decisions.")}`;
}

export function renderGuide(repository: ValidatedRepository) {
  return `${marker}
# Maintainer guide

LORE treats maintainer output as untrusted. Read \`${repository.manifest.maintenance.skill}\`, inspect the exact-revision evidence in the context packet, and return exactly one \`lore-proposal/v1\` artifact.

## Maintenance cycle

1. Run \`lore extract\` and \`lore validate\`.
2. Define a bounded task and run \`lore context <task.yaml>\`.
3. Follow the repository-local skill and write the proposal to \`${repository.manifest.paths.proposals}/\`.
4. Run \`lore validate-proposal <proposal.yaml>\`.
5. Review semantic correctness, identity, evidence, uncertainty, and supersession.
6. Run \`lore apply <proposal.yaml>\` only after review.
7. Run \`lore project --check\`, \`lore diff <base> HEAD\`, and \`lore verify-self\`.

## Accepted procedures

${renderRecordList(records(repository, "procedure"), "No active procedure records.")}

## Active constraints

${renderRecordList(records(repository, "constraint"), "No active constraints.")}

Never edit generated documentation, extracted facts, accepted records, or transaction receipts directly.
`;
}

export function renderTrustModel(repository: ValidatedRepository) {
  return `${marker}
# Trust model

LORE assumes repository paths, documents, source files, Git revisions, historical evidence, and maintainer proposals may be malformed or adversarial. Validation depends on exact repository state and public contracts rather than a trusted agent identity.

## Authority model

| Surface | Role | Authority |
|---|---|---|
| Source code and configuration | Executable repository behavior | Authoritative for implemented behavior |
| \`lore.yaml\` and schemas | Repository and protocol contracts | Authoritative configuration and validation rules |
| \`${repository.manifest.paths.extracted}/\` | Deterministic observations | Replaceable facts generated from repository state |
| \`${repository.manifest.paths.records}/\` | Reviewed semantic knowledge | Append-only accepted history |
| \`${repository.manifest.paths.transactions}/\` | Acceptance history | Immutable receipts for applied proposals |
| Generated documentation | Human-readable views | Non-authoritative deterministic projections |
| Maintainer proposals | Candidate changes | Untrusted until validated, reviewed, and applied |

## Accepted decisions

${renderRecordList(records(repository, "decision"), "No active decisions.")}

## Active constraints

${renderRecordList(records(repository, "constraint"), "No active constraints.")}

## Known trust limitations

${renderRecordList(records(repository, "finding"), "No active findings.")}

## Verification

Use \`lore validate\` to check repository invariants, \`lore project --check\` to detect projection drift, and \`lore verify-self\` to verify the complete self-hosted trust root.
`;
}

export function renderAuthorityAndFileOwnership(repository: ValidatedRepository) {
  const paths = repository.manifest.paths;
  return `${marker}
# Authority and file ownership

Every committed LORE surface has one owner and one mutation path. A generated file is never repaired by editing the projection itself.

| Surface | Classification | Direct editing | Owner or regeneration path |
|---|---|---|---|
| \`lore.yaml\` | Authoritative configuration | Yes, with schema review | Repository maintainer |
| \`schemas/\` | Authoritative protocol contracts | Yes, with compatibility review | Schema implementation |
| \`${paths.extracted}/\` | Deterministic generated facts | No | \`lore extract\` |
| \`${paths.records}/\` | Accepted semantic history | No in-place edits | Validated \`lore-proposal/v1\` through \`lore apply\` |
| \`${paths.proposals}/\` | Untrusted candidate input | Yes | Human or external maintainer |
| \`${paths.transactions}/\` | Accepted transaction receipts | No | \`lore apply\` |
| \`${paths.generated_docs}/\` | Deterministic documentation | No | \`lore project\` |
| \`${paths.skills}/\` | Versioned maintainer protocol | Yes, with digest and compatibility review | Repository maintainer |
| Local caches and dependency stores | Runtime state | Local only | Package manager or operating environment |

## Safe change order

1. Change implementation, configuration, schemas, or other authoritative source.
2. Regenerate deterministic facts with \`lore extract\`.
3. Generate bounded maintainer context.
4. Validate and review one proposal.
5. Apply the accepted transaction.
6. Regenerate projections with \`lore project\`.
7. Verify the final tree and review the semantic diff.
`;
}

export function renderAdoptionTutorial(repository: ValidatedRepository) {
  return `${marker}
# Adopt LORE

This tutorial installs LORE in an existing Git repository, establishes the trust root, and proves that the repository converges to deterministic state.

## 1. Start from a clean Git repository

\`\`\`bash
git status --short
npm install --save-dev @laurajoyhutchins/lore
npm exec -- lore version --json
\`\`\`

Commit or discard unrelated work before initialization. LORE evidence and proposal validation are revision-sensitive.

## 2. Install the bootstrap trust root

\`\`\`bash
npm exec -- lore init --id example-repository --name "Example Repository"
\`\`\`

Review \`lore.yaml\`, \`BOOTSTRAP.md\`, \`schemas/\`, and \`${repository.manifest.maintenance.skill}\`. Initialization must not silently replace accepted records or transactions.

## 3. Generate deterministic facts

\`\`\`bash
npm exec -- lore extract
npm exec -- lore validate
\`\`\`

Inspect \`${repository.manifest.paths.extracted}/\`. Extracted facts describe repository state but do not assert architectural intent.

## 4. Generate initial projections

\`\`\`bash
npm exec -- lore project
npm exec -- lore project --check
\`\`\`

Generated files are views. Do not edit them directly.

## 5. Complete semantic orientation

Create a bounded task describing the repository purpose, components, decisions, constraints, findings, and procedures that need review. Run:

\`\`\`bash
npm exec -- lore context .lore/tasks/initial-orientation.yaml \\
  > .lore/context/initial-orientation.yaml
\`\`\`

Give that packet and the repository-local skill to a human or model maintainer. The required output is exactly one \`lore-proposal/v1\` artifact.

## 6. Validate and apply the first proposal

\`\`\`bash
npm exec -- lore validate-proposal .lore/proposals/initial-orientation.yaml
npm exec -- lore apply .lore/proposals/initial-orientation.yaml
\`\`\`

Review the proposal semantically before applying it. Schema validity does not prove that an interpretation is correct.

## 7. Prove convergence

\`\`\`bash
npm exec -- lore extract --check
npm exec -- lore validate
npm exec -- lore project --check
npm exec -- lore verify-self
git diff --exit-code
\`\`\`

Commit the trust root, accepted records, transaction receipt, extracted facts, and generated projections together after review.
`;
}

export function renderMaintenanceWorkflow(repository: ValidatedRepository) {
  return `${marker}
# Maintain repository knowledge

Use this workflow after a repository change that may affect architecture, responsibilities, decisions, constraints, findings, relationships, or operating procedures.

## 1. Establish exact state

\`\`\`bash
BASE="$(git rev-parse HEAD)"
npm exec -- lore extract
npm exec -- lore validate
\`\`\`

## 2. Define and hydrate a bounded task

Create a task with precise paths, component IDs, tags, audiences, and an explicit history flag. Then run:

\`\`\`bash
npm exec -- lore context .lore/tasks/change.yaml \\
  > .lore/context/change.yaml
\`\`\`

The packet identifies selected records, selection reasons, evidence, validation commands, the skill path, and the proposal destination.

## 3. Produce one proposal

Follow \`${repository.manifest.maintenance.skill}\`. Return either:

- \`changes_proposed\` with append or transition operations; or
- \`no_documentation_change\` with a concrete reason and zero operations.

## 4. Validate and review

\`\`\`bash
npm exec -- lore validate-proposal .lore/proposals/change.yaml
\`\`\`

Review claim-to-evidence correspondence, stable identity, next revision, supersession, status, conflicts, uncertainty, and whether a no-change result would be more accurate.

## 5. Apply transactionally

\`\`\`bash
npm exec -- lore apply .lore/proposals/change.yaml
npm exec -- lore project --check
npm exec -- lore verify-self
\`\`\`

## 6. Commit and inspect semantic history

Review the working-tree changes, commit the accepted transaction and regenerated outputs, then compare exact revisions:

\`\`\`bash
git add .
git commit -m "docs: update LORE knowledge"
TARGET="$(git rev-parse HEAD)"
npm exec -- lore diff "$BASE" "$TARGET"
npm exec -- lore explain lore://<repository>/<kind>/<id>@<revision>
\`\`\`

## Accepted procedures

${renderRecordList(records(repository, "procedure"), "No active procedure records.")}
`;
}

export function renderProposalReview(repository: ValidatedRepository) {
  return `${marker}
# Review a LORE proposal

A proposal can be structurally valid and still be semantically wrong. Review it as an untrusted interpretation of exact repository evidence.

## Mechanical gate

\`\`\`bash
npm exec -- lore validate-proposal .lore/proposals/change.yaml
\`\`\`

Do not continue if the base revision, referenced skill digest, schema, evidence, identity, revision, supersession, status transition, or cross-record references fail validation.

## Semantic review checklist

- Does every factual assertion follow from the cited path at the cited full commit SHA?
- Is observed behavior kept distinct from architectural intent?
- Is the selected record kind correct: repository, component, relationship, decision, finding, constraint, or procedure?
- Does an existing stable record ID already represent the concept?
- Is the proposed revision exactly the next positive revision?
- Does \`supersedes\` identify the correct prior accepted record?
- Are active decisions and constraints reconciled rather than silently contradicted?
- Are uncertainty and unsupported environments recorded explicitly?
- Is the proposal narrower than the evidence, or broader than the task requires?
- Would \`no_documentation_change\` be more accurate?

## Active repository constraints

${renderRecordList(records(repository, "constraint"), "No active constraints.")}

## Apply only after review

\`\`\`bash
npm exec -- lore apply .lore/proposals/change.yaml
npm exec -- lore verify-self
\`\`\`
`;
}

export function renderCliReference(repository: ValidatedRepository) {
  return `${marker}
# CLI reference

The installed \`lore\` command is the supported public API. Internal TypeScript modules are not a library compatibility surface.

## Commands

${CLI_REFERENCE.map(
  ([name, syntax, description]) =>
    `### \`${name}\`\n\n${syntax}\n\n${description}\n`,
).join("\n")}

## Global behavior

- \`--help\` prints stable command help.
- \`--json\` selects JSON for commands that expose it.
- \`--check\` compares generated state without writing for extraction and projection.
- \`--force\` is limited to initialization and does not authorize rewriting accepted history.
- Commands fail nonzero on invalid usage, validation failure, stale generated output, unsafe paths, stale revisions, or transaction failure.
- Normal operation is repository-local and does not require network access.

## Repository paths

- Extracted facts: \`${repository.manifest.paths.extracted}/\`
- Accepted records: \`${repository.manifest.paths.records}/\`
- Proposals: \`${repository.manifest.paths.proposals}/\`
- Transactions: \`${repository.manifest.paths.transactions}/\`
- Generated documentation: \`${repository.manifest.paths.generated_docs}/\`
`;
}

export function renderDataModelReference(repository: ValidatedRepository) {
  return `${marker}
# Data model reference

LORE keeps deterministic observations, reviewed interpretations, candidate changes, accepted transactions, and generated views separate.

## Manifest

\`lore.yaml\` declares repository identity, owned paths, enabled extractors, deterministic projections, the maintainer skill, the proposal schema, and hydration limits. Unknown schema versions and projection IDs fail closed.

## Semantic record envelope

Every accepted record has a stable ID, kind, positive revision, immutable status, title, summary, scope, exact Git evidence, disclosure metadata, provenance, optional supersession reference, and a payload object. Schema version 1 reserves payload meaning for each record kind without yet imposing kind-specific payload sub-schemas.

| Kind | Purpose |
|---|---|
| \`repository\` | Repository purpose, boundaries, entry points, and support state |
| \`component\` | Responsibilities, owned paths, interfaces, dependencies, and invariants |
| \`relationship\` | A typed connection among accepted records or extracted components |
| \`decision\` | A chosen design with rationale, alternatives, and consequences |
| \`finding\` | A verified defect, limitation, risk, or technical-debt item |
| \`constraint\` | A rule that must remain true across implementation and operation |
| \`procedure\` | A repeatable workflow with prerequisites, steps, expected results, and failure handling |

Accepted revisions live beneath \`${repository.manifest.paths.records}/<kind>/<id>/<revision>.yaml\`. Corrections append a new revision and preserve lineage through \`supersedes\`.

## Evidence references

Evidence uses a full 40-character Git commit SHA plus a repository-relative path. A reference may add a symbol or validated line range. Generated prose cannot be the sole evidence for a semantic assertion.

## Task and hydration

A task declares an ID, title, description, paths, component IDs, tags, audiences, and whether superseded history is eligible. Hydration scores records deterministically, reports selection reasons, includes direct evidence, and reports omitted records.

## Maintainer context and proposal

\`lore-maintainer-context/v1\` wraps the validated task, hydration packet, skill path, output schema, and proposal destination. A \`lore-proposal/v1\` artifact returns either candidate operations or a first-class no-change result.

## Transaction receipt

An accepted proposal writes new immutable record revisions, a transaction receipt beneath \`${repository.manifest.paths.transactions}/\`, and regenerated projections. Application plans the complete candidate state before writing and rolls back failed writes.

## Projection

Generated Markdown begins with the LORE marker, contains no current time or machine-specific absolute paths, uses stable ordering, and must be byte-identical for unchanged authoritative inputs.
`;
}
