import { recordReference } from "../domain/references.js";
import type { SemanticRecord, ValidatedRepository } from "../domain/types.js";

const marker = "<!-- Generated by LORE. Do not edit directly. -->";
const esc = (value: string) => value.replace(/\|/g, "\\|").replace(/#/g, "\\#");
const active = (record: SemanticRecord, repository: ValidatedRepository) =>
  repository.effectiveStatus.get(
    recordReference(repository.manifest.repository.id, record),
  ) !== "superseded";

export function renderReadme(repository: ValidatedRepository) {
  return `${marker}
# ${esc(repository.manifest.repository.name)}

**LORE Organizes Repository Evidence** is an agent-neutral, Git-backed system for turning repository evidence and reviewed semantic records into human documentation and bounded maintainer context.

> **Project status:** pre-1.0 and under active development. Schemas, commands, and public APIs may change before the first stable release.

## What LORE does

LORE separates repository knowledge into two layers:

- **Deterministic facts** extracted from source, configuration, package metadata, imports, and tests.
- **Reviewed semantic records** that capture intent, architecture, decisions, constraints, findings, and procedures that code alone cannot prove.

From those inputs, LORE produces deterministic documentation projections, explainable task-context hydration, semantic history comparisons, and validated append-only maintenance transactions.

LORE does not host an LLM, require a model provider, run autonomous schedules, use a vector database, or treat an agent identity as authorization. It is compatible with external development workflows, including Superpowers, but does not depend on them.

## Requirements

- Git
- Node.js 22 or newer
- Corepack
- pnpm 10.14.0

## Quick start

\`\`\`bash
node scripts/restore-verified-lockfile.mjs
corepack enable
pnpm install --frozen-lockfile
pnpm typecheck
pnpm lint
pnpm test
pnpm build
pnpm lore --help
pnpm lore verify-self
\`\`\`

The standard \`pnpm-lock.yaml\` is restored byte-for-byte from the content-addressed members under \`artifacts/verified-lockfile/\`. The release gate verifies every member, the reconstructed SHA-256, and the Git blob identity before installation, then removes a gate-created lockfile before checking for a clean tree.

The repository currently keeps \`"private": true\` in \`package.json\` to prevent accidental npm publication. That does not prevent the GitHub repository itself from being public.

## Core workflow

1. \`lore init\` installs the bootstrap trust root in a repository.
2. \`lore extract\` regenerates deterministic repository facts.
3. \`lore validate\` checks manifests, schemas, records, evidence, paths, and semantic invariants.
4. \`lore project\` regenerates human-facing documentation.
5. \`lore context\` and \`lore hydrate\` select bounded, explainable task context.
6. \`lore validate-proposal\` treats maintainer output as untrusted and validates it against the public protocol.
7. \`lore apply\` plans and records accepted changes transactionally.
8. \`lore diff\` and \`lore explain\` describe semantic history.
9. \`lore verify-self\` checks that LORE's own trust root, facts, records, projections, history, and deterministic outputs remain coherent.

Run \`pnpm lore --help\` for the command list. LORE is self-hosting: this README and the files under \`docs/generated/\` are projections produced by LORE itself.

## Trust model

Repository documents, paths, Git revisions, source files, and maintainer proposals are untrusted inputs. LORE is designed to fail closed when it cannot prove schema validity, repository containment, evidence provenance, revision identity, append-only history, transactional integrity, or deterministic output.

Generated prose is useful but non-authoritative. The source of truth is the combination of source code, \`lore.yaml\`, schemas, extracted facts, accepted semantic records, accepted transactions, and the included maintenance skill.

## Documentation

- [Bootstrap trust root](BOOTSTRAP.md)
- [Design specification](docs/superpowers/specs/2026-07-28-lore-design.md)
- [Generated architecture](docs/generated/architecture.md)
- [Generated component catalog](docs/generated/component-catalog.md)
- [Generated current decisions](docs/generated/current-decisions.md)
- [Maintainer skill](skills/maintain-repository-documentation/SKILL.md)
- [Contribution guide](CONTRIBUTING.md)
- [Security policy](SECURITY.md)

## Contributing and security

Contributions are welcome within the repository's evidence, determinism, and append-only-history contracts. Read [CONTRIBUTING.md](CONTRIBUTING.md) before changing source, schemas, semantic records, or generated documentation.

Report suspected vulnerabilities privately as described in [SECURITY.md](SECURITY.md). Do not disclose exploit details in a public issue.

## License

LORE is licensed under the [Apache License 2.0](LICENSE).
`;
}

export function renderRepositoryCard(repository: ValidatedRepository) {
  return `${marker}
# Repository card

- ID: \`${repository.manifest.repository.id}\`
- Records: ${repository.records.length}
`;
}

export function renderArchitecture(repository: ValidatedRepository) {
  const components = repository.records
    .filter((record) => record.kind === "component" && active(record, repository))
    .sort((left, right) => left.title.localeCompare(right.title));
  return `${marker}
# Architecture

${components.map((component) => `## ${esc(component.title)}\n\n${component.summary}\n`).join("\n")}`;
}

export function renderCatalog(repository: ValidatedRepository) {
  const components = repository.records
    .filter((record) => record.kind === "component")
    .sort((left, right) => left.title.localeCompare(right.title));
  return `${marker}
# Component catalog

| Component | Status | Summary |
|---|---|---|
${components
  .map(
    (component) =>
      `| ${esc(component.title)} | ${repository.effectiveStatus.get(
        recordReference(repository.manifest.repository.id, component),
      )} | ${esc(component.summary)} |`,
  )
  .join("\n")}
`;
}

export function renderDecisions(repository: ValidatedRepository) {
  const decisions = repository.records
    .filter((record) => record.kind === "decision" && active(record, repository))
    .sort((left, right) => left.title.localeCompare(right.title));
  return `${marker}
# Current decisions

${decisions.map((decision) => `## ${esc(decision.title)}\n\n${decision.summary}\n`).join("\n")}`;
}

export function renderGuide(repository: ValidatedRepository) {
  return `${marker}
# Maintainer guide

Read \`${repository.manifest.maintenance.skill}\`, inspect evidence, and return one \`lore-proposal/v1\` artifact. Never edit generated documentation or accepted history directly.
`;
}
